# show_variables.rb
# command: ruby show_variables.rb

# Define your variables here
IP_RANGE = "172.16.16."
VAGRANT_BOX = "centos/7"
VAGRANT_BOX_VERSION = "2004.01"
CPUS_MASTER_NODE = 2
CPUS_WORKER_NODE = 2
MEMORY_MASTER_NODE = 2048
MEMORY_WORKER_NODE = 1024
MASTER_NODES_COUNT = 2
WORKER_NODES_COUNT = 2
CLUSTER_NAME = "k8s-3"
MASTER_NODE_NAME = "master"
WORKER_NODE_NAME = "worker"
MASTER_LOAD_BALANCER_NAME = "lb-master"
WORKER_LOAD_BALANCER_NAME = "lb-worker"
MASTER_LOAD_BALANCER_IP = "#{IP_RANGE}#{210}"
WORKER_LOAD_BALANCER_IP = "#{IP_RANGE}#{220}"

IP_MASTER_LIST = (1..MASTER_NODES_COUNT).map do |i|
  "#{IP_RANGE}#{100 + i} #{MASTER_NODE_NAME}-#{i} #{MASTER_NODE_NAME}-#{i}"
end.join(",")

IP_WORKER_LIST = (1..WORKER_NODES_COUNT).map do |i|
  "#{IP_RANGE}#{200 + i} #{WORKER_NODE_NAME}-#{i} #{WORKER_NODE_NAME}-#{i}"
end.join(",")

# Print the variable values
puts "IP_RANGE: #{IP_RANGE}"
puts "VAGRANT_BOX: #{VAGRANT_BOX}"
puts "VAGRANT_BOX_VERSION: #{VAGRANT_BOX_VERSION}"
puts "CPUS_MASTER_NODE: #{CPUS_MASTER_NODE}"
puts "CPUS_WORKER_NODE: #{CPUS_WORKER_NODE}"
puts "MEMORY_MASTER_NODE: #{MEMORY_MASTER_NODE}"
puts "MEMORY_WORKER_NODE: #{MEMORY_WORKER_NODE}"
puts "MASTER_NODES_COUNT: #{MASTER_NODES_COUNT}"
puts "WORKER_NODES_COUNT: #{WORKER_NODES_COUNT}"
puts "CLUSTER_NAME: #{CLUSTER_NAME}"
puts "MASTER_NODE_NAME: #{MASTER_NODE_NAME}"
puts "WORKER_NODE_NAME: #{WORKER_NODE_NAME}"
puts "MASTER_LOAD_BALANCER_NAME: #{MASTER_LOAD_BALANCER_NAME}"
puts "WORKER_LOAD_BALANCER_NAME: #{WORKER_LOAD_BALANCER_NAME}"
puts "MASTER_LOAD_BALANCER_IP: #{MASTER_LOAD_BALANCER_IP}"
puts "WORKER_LOAD_BALANCER_IP: #{WORKER_LOAD_BALANCER_IP}"
puts "IP_MASTER_LIST: #{IP_MASTER_LIST}"
puts "IP_WORKER_LIST: #{IP_WORKER_LIST}"
