# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "centos/7"
VAGRANT_BOX_VERSION = "2004.01"

CPUS_MASTER_NODE    = 2
CPUS_WORKER_NODE    = 1

MEMORY_MASTER_NODE  = 2048
MEMORY_WORKER_NODE  = 1024

MASTER_NODES_COUNT  = 3
WORKER_NODES_COUNT  = 1


Vagrant.configure(2) do |config|

  # config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Nodes
  (1..MASTER_NODES_COUNT).each do |i|

    config.vm.define "master#{i}" do |masternode|

      masternode.vm.box               = VAGRANT_BOX
      masternode.vm.box_check_update  = false
      masternode.vm.box_version       = VAGRANT_BOX_VERSION
      masternode.vm.hostname          = "master#{i}.example.com"

      masternode.vm.network "private_network", ip: "172.16.16.10#{i}"

      masternode.vm.provider :virtualbox do |v|
        v.name   = "master#{i}"
        v.memory = MEMORY_MASTER_NODE
        v.cpus   = CPUS_MASTER_NODE
      end
    
      masternode.vm.provider :libvirt do |v|
        v.nested  = true
        v.memory  = MEMORY_MASTER_NODE
        v.cpus    = CPUS_MASTER_NODE
      end

      masternode.vm.provision "shell", path: "bootstrap.sh"
      masternode.vm.provision "shell", path: "lb.sh"
      masternode.vm.provision "shell", path: "bootstrap_kmaster.sh"

    end

  end


  # # Kubernetes Worker Nodes
  (1..WORKER_NODES_COUNT).each do |i|

    config.vm.define "worker#{i}" do |node|

      node.vm.box               = VAGRANT_BOX
      node.vm.box_check_update  = false
      node.vm.box_version       = VAGRANT_BOX_VERSION
      node.vm.hostname          = "worker#{i}.example.com"

      node.vm.network "private_network", ip: "172.16.16.20#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "worker#{i}"
        v.memory  = MEMORY_WORKER_NODE
        v.cpus    = CPUS_WORKER_NODE
      end

      node.vm.provider :libvirt do |v|
        v.memory  = MEMORY_WORKER_NODE
        v.nested  = true
        v.cpus    = CPUS_WORKER_NODE
      end

      node.vm.provision "shell", path: "bootstrap.sh"
      node.vm.provision "shell", path: "bootstrap_kworker.sh"

    end

  end

end
